threads = 10
verbose = true
retries = 3
subdomains = false
parameters = true
providers = ["wayback","commoncrawl","otx","urlscan"]
blacklist = ["ttf","woff","svg","png","jpg"]
json = false

#api keys
[urlscan]
  apikey = ""
[otx]
  apikey = ""

#filters
[filters]
  from = ""
  to = ""
  matchstatuscodes = [200, 301, 302]
  matchmimetypes = []
  filterstatuscodes = [404, 500, 403]
  filtermimetypes = [
      "image/png",
      "image/jpg",
      "image/svg+xml"
  ]